version: 2.0

defaults: &defaults
  working_directory: /go/src/github.com/sylabs/singularity

jobs:
  get_source:
    <<: *defaults
    docker:
      - image: sylabsio/golang:1.11-stretch
    steps:
      - checkout
      - restore_cache:
          key: dep-cache-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor
      - run:
          name: Set Up Vendor Directory
          command: |-
            if [ ! -d vendor ]; then
              dep ensure -vendor-only
            fi
      - save_cache:
          key: dep-cache-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor
      - persist_to_workspace:
          root: /go
          paths:
            - src/github.com/sylabs/singularity

  go1.10-stretch:
    <<: *defaults
    docker:
      - image: sylabsio/golang:1.10-stretch
    steps:
      - attach_workspace:
          at: /go
      - run:
          name: Build Singularity
          command: |-
            ./mconfig -p /usr/local
            make -j$(nproc) -C ./builddir all

  go1.11-stretch:
    <<: *defaults
    docker:
      - image: sylabsio/golang:1.11-stretch
    steps:
      - attach_workspace:
          at: /go
      - run:
          name: Build Singularity
          command: |-
            ./mconfig -p /sroot
            make -j$(nproc) -C ./builddir all
      - persist_to_workspace:
          root: /go
          paths:
            - src/github.com/sylabs/singularity

  go1.11-alpine:
    <<: *defaults
    docker:
      - image: sylabsio/golang:1.11-alpine
    steps:
      - attach_workspace:
          at: /go
      - run:
          name: Build Singularity
          command: |-
            ./mconfig -p /usr/local
            make -j$(nproc) -C ./builddir all

  unit_test:
    machine: true
    environment:
      GOPATH: /go
      GOROOT: /usr/local/go
      PATH: /go/bin:/usr/local/go/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
    working_directory: ~/
    steps:
      - run:
          name: Update Go to 1.11
          command: |-
            cd /tmp
            wget https://dl.google.com/go/go1.11.linux-amd64.tar.gz
            sudo tar -xvf go1.11.linux-amd64.tar.gz
            sudo mv go /usr/local
      - attach_workspace:
          at: /go
      - run:
          name: fetch deps
          command: |-
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            go get -u golang.org/x/lint/golint
        <<: *defaults
      - run:
          name: install
          command: |-
            ./mconfig -p /usr/local
            make -j `nproc 2>/dev/null || echo 1` -C ./builddir all
            sudo make -C ./builddir install

workflows:
  version: 2
  test-compile:
    jobs:
      - get_source
      - go1.10-stretch:
          requires:
            - get_source
      - go1.11-stretch:
          requires:
            - get_source
      - go1.11-alpine:
          requires:
            - get_source
      - singularity_tests:
          requires:
            - go1.11-stretch
