version: 2.0

defaults: &defaults
  working_directory: /go/src/github.com/sylabs/singularity
  
jobs:
  get_source:
    <<: *defaults
    docker:
      - image: sylabsio/golang:1.11-stretch
    steps:
      - checkout
      - restore_cache:
          key: dep-cache-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor
      - run:
          name: Set Up Vendor Directory
          command: |-
            if [ ! -d vendor ]; then
              dep ensure -vendor-only
            fi
      - save_cache:
          key: dep-cache-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor
      - persist_to_workspace:
          root: /go
          paths:
            - src/github.com/sylabs/singularity

  go1.10-stretch:
    <<: *defaults
    docker:
      - image: sylabsio/golang:1.10-stretch
    steps:
      - attach_workspace:
          at: /go
      - run:
          name: Build Singularity
          command: |-
            ./mconfig -p /usr/local
            make -j$(nproc) -C ./builddir all

  go1.11-stretch:
    <<: *defaults
    docker:
      - image: sylabsio/golang:1.11-stretch
    steps:
      - attach_workspace:
          at: /go
      - run:
          name: Build Singularity
          command: |-
            ./mconfig -p /sroot/usr/local
            make -j$(nproc) -C ./builddir all
      - run: #Only run make check on go1.11 as it introduces a new formatting rule we're following
          name: Run checks
          command: make -C ./builddir check
      - persist_to_workspace:
          root: /go
          paths:
            - src/github.com/sylabs/singularity/builddir

  go1.11-alpine:
    <<: *defaults
    docker:
      - image: sylabsio/golang:1.11-alpine
    steps:
      - attach_workspace:
          at: /go
      - run:
          name: Build Singularity
          command: |-
            ./mconfig -p /usr/local
            make -j$(nproc) -C ./builddir all

  singularity_tests:
    working_directory: ~/go/src/github.com/sylabs/singularity
    machine: true
    steps:
      - run:
          name: Update VM
          command: |-
            sudo apt-get update
            sudo apt-get install -y ca-certificates
      - attach_workspace:
          at: ~/go
      - run:
          name: Install dep
          command: |-
            go get -u github.com/golang/dep/cmd/dep
      - run:
          name: Install Singularity
          command: |-
            sed -i -e 's|/go/src/github.com/|/home/circleci/go/src/github.com/|g' builddir/Makefile builddir/mergeddeps builddir/src/runtime/c/lib/util/*
            sudo make -C builddir/ install

workflows:
  version: 2
  test-compile:
    jobs:
      - get_source
      - go1.10-stretch:
          requires:
            - get_source
      - go1.11-stretch:
          requires:
            - get_source
      - go1.11-alpine:
          requires:
            - get_source
      - singularity_tests:
          requires:
            - go1.11-stretch

