version: 2.0

defaults: &defaults
  working_directory: /go/src/github.com/sylabs/singularity
  
jobs:
  get_source:
    <<: *defaults
    docker:
      - image: sylabsio/golang:1.11-stretch
    steps:
      - checkout
      - restore_cache:
          key: dep-cache-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor
      - run:
          name: Set Up Vendor Directory
          command: |-
            if [ ! -d vendor ]; then
              dep ensure -vendor-only
            fi
      - save_cache:
          key: dep-cache-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor
      - persist_to_workspace:
          root: /go
          paths:
            - src/github.com/sylabs/singularity

  go1.10-stretch:
    <<: *defaults
    docker:
      - image: sylabsio/golang:1.10-stretch
    steps:
      - attach_workspace:
          at: /go
      - run:
          name: Build Singularity
          command: |-
            ./mconfig -p /usr/local
            make -j$(nproc) -C ./builddir all

  go1.11-stretch:
    <<: *defaults
    docker:
      - image: sylabsio/golang:1.11-stretch
    steps:
      - attach_workspace:
          at: /go
      - run:
          name: Build Singularity
          command: |-
            ./mconfig -p /sroot/usr/local
            make -j$(nproc) -C ./builddir all
      - persist_to_workspace:
          root: /go
          paths:
            - src/github.com/sylabs/singularity/builddir

  go1.11-alpine:
    <<: *defaults
    docker:
      - image: sylabsio/golang:1.11-alpine
    steps:
      - attach_workspace:
          at: /go
      - run:
          name: Build Singularity
          command: |-
            ./mconfig -p /usr/local
            make -j$(nproc) -C ./builddir all

  singularity_tests:
    machine: true
    environment:
      GOPATH: /go
    steps:
      - run:
          name: Create go path for root workspace
          command: |-
            sudo mkdir -p /go/src/github.com/sylabs/singularity
            sudo chown -R circleci:circleci /go
      - attach_workspace:
          at: /go
      - run:
          name: Install dep
          <<: *defaults
          command: |-
            go get -u github.com/golang/dep/cmd/dep
      - run:
          name: Install Singularity
          <<: *defaults
          command: |-
            sudo -E make -C builddir/ install

workflows:
  version: 2
  test-compile:
    jobs:
      - get_source
      - go1.10-stretch:
          requires:
            - get_source
      - go1.11-stretch:
          requires:
            - get_source
      - go1.11-alpine:
          requires:
            - get_source
      - singularity_tests:
          requires:
            - go1.11-stretch

